// Auto-generated by sync-phase-names.ts DO NOT EDIT
// Source: extensions/stelow/types.ts PHASE_NAMES

export const PHASE_NAMES: Record<number, string> = {
  1: "Setup",
  2: "Context",
  3: "Shape",
  4: "Critique",
  5: "Gate",
  6: "Scope",
  7: "Interface",
  8: "Int.Gate",
  9: "Selection",
  10: "Planning",
  11: "Execution",
  12: "Verification",
  13: "Audit",
};

export const MAX_PHASE = 13;
