/**
 * sync-phase-names.ts
 *
 * Reads PHASE_NAMES from extensions/cali-product-workflow/types.ts (source of truth)
 * and generates src/phase-names.generated.ts for the OpenCode plugin.
 *
 * Run: bun run sync-phase-names
 * Check: the generated file should never be hand-edited.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Source of truth: project's types.ts
const TYPES_PATH = resolve(__dirname, "../../../extensions/cali-product-workflow/types.ts");
const OUT_PATH = resolve(__dirname, "src/phase-names.generated.ts");

// Read types.ts and extract PHASE_NAMES array
const content = readFileSync(TYPES_PATH, "utf-8");
const match = content.match(/export const PHASE_NAMES\s*=\s*\[([\s\S]*?)\];/);
if (!match) {
  console.error("❌ Could not find PHASE_NAMES in", TYPES_PATH);
  process.exit(1);
}

// Parse the array — extract quoted strings
const rawArray = match[1];
const namePattern = /"([^"]+)"/g;
const names: string[] = [];
let m;
while ((m = namePattern.exec(rawArray)) !== null) {
  names.push(m[1]);
}

if (names.length === 0) {
  console.error("❌ Could not parse any phase names from PHASE_NAMES array");
  process.exit(1);
}

// Generate the Record<number, string> mapping
// Plugin starts at index 2 (Setup), skipping Triage (0) and ItemSelect (1)
const lines: string[] = [];
lines.push("// Auto-generated by sync-phase-names.ts DO NOT EDIT");
lines.push("// Source: extensions/cali-product-workflow/types.ts PHASE_NAMES");
lines.push("");
lines.push("export const PHASE_NAMES: Record<number, string> = {");

let key = 1;
let skipped = 0;
for (const name of names) {
  if (skipped < 2) {
    // Skip Triage (0) and ItemSelect (1) — plugin starts at Setup
    skipped++;
    continue;
  }
  lines.push(`  ${key}: "${name}",`);
  key++;
}
lines.push("};");
lines.push("");

// Also export MAX_PHASE for dynamic boundary checks
const maxKey = key - 1;
lines.push(`export const MAX_PHASE = ${maxKey};`);
lines.push("");

const generated = lines.join("\n");
writeFileSync(OUT_PATH, generated, "utf-8");

console.log(`✅ Generated ${OUT_PATH}`);
console.log(`   ${names.length} phases in source, ${key - 1} phases mapped (skipped ${skipped} for Triage/ItemSelect)`);
